### ISSUE TITLE
How to fix error Cannot query field "path" on type "GithubContributors"

### ISSUE THREAD

**Issue by emexal-company** [adobe/gatsby-theme-aio#190] opened 2021-01-13 09:15 UTC
# ❔ Question
After running `npm run dev`, I have always the error 
```
error There was an error in your GraphQL query:
Cannot query field "path" on type "GithubContributors".
```
Can you please suggest what is wrong, and what am I missing ?

## 🔦 Context

I'm trying to build a website for my company, using the gatsby theme based on Adobe Spectrum.

## 🌍 Your Environment

Windows x64, NodeJS v14.15.4, npm 6.14.10

.env file content
```
REPO_GITHUB_TOKEN=xxxxxxxxxxx
REPO_OWNER=AdobeDocs
REPO_NAME=dev-site-documentation-template
REPO_BRANCH=main
```

## 🧢 Your Company/Team
EMEXAL

**Comment by icaraps** [comment] 2021-01-13 09:35
It could be because your repository and some `md` files in that repository are not pushed on GitHub or `REPO_OWNER` and `REPO_NAME` don't match your GitHub organization and repository name.

**Comment by emexal-company** [comment] 2021-01-13 09:51
Actually, nothing was pushed on GitHub. I've pushed everything now, but I can still see that the github token has never been used.

**Comment by emexal-company** [comment] 2021-01-13 14:26
I'm wondering if the .env file is in the right place. I have it in the same directory as package.json. @icaraps do you think this is OK ?

**Comment by icaraps** [comment] 2021-01-13 14:35
@emexal-company Yes that's fine. I don't know the details of your use case but you only need env for local development and if you're building a doc site like https://github.com/AdobeDocs/dev-site-documentation-template.

**Comment by emexal-company** [comment] 2021-01-13 14:51
My original requirement is to create a website using Gatsby + Spectrum. I have followed the steps in the README, but nothing shows up (apart the error mentioned here), when I wrote `npm run dev`. Remark: I'm a beginnger in Gatsby, and it will be my first website using this framework.

I thought it was easy to startup with the README, but I'm really struggling from a few days...

I'm performing some debugging. githubFetch from gql.js is never called... So I still don't understand how the github API will be called. I can see also that the writen values in my .env file are correctly visible in the variables process.env.REPO_, when placing a breakpoint inside gatsby-config.js

**Comment by icaraps** [comment] 2021-01-13 15:02
@emexal-company to get started quickly I recommend to use one the templates eg https://github.com/adobedocs/dev-site-product-template/. On that page there's a green button "Use this template". You can click on it and it will create the repository for you. Then run the commands `npm i && npm run dev`.

**Comment by emexal-company** [comment] 2021-01-13 15:54
I tried like you said, but I got exactely the same error.

**Comment by icaraps** [comment] 2021-01-13 16:11
OK strange could you please share a repository url to reproduce the issue ? @shazron do you think it could be related to Windows x64 ?

**Comment by emexal-company** [comment] 2021-01-13 16:24
The repository I'm using is the following https://github.com/emexal-company/spectrum-gatsby

**Comment by shazron** [comment] 2021-01-14 05:54
Steps:
```
git clone https://github.com/adobedocs/dev-site-product-template/
cd dev-site-product-template
npm i
npm run dev
```

I can repro on Windows 10 x64 (in a VM). I cannot repro on macOS 11.0.1 Big Sur.

**Comment by icaraps** [comment] 2021-01-14 10:30
Thanks @shazron for confirming there's an issue when using Windows. I've submitted a fix can you please review and merge if all fine https://github.com/adobe/gatsby-source-github-file-contributors/pull/8 ?

**Comment by shazron** [comment] 2021-01-15 02:48
Reviewed and merged. Published https://github.com/adobe/gatsby-source-github-file-contributors/releases/tag/0.3.1

**Comment by emexal-company** [comment] 2021-01-15 10:02
From my side, I tested it, and it fixed the problem. Isn't it better also to update the dependency inside `package.json` ?

https://github.com/adobe/gatsby-theme-aio/blob/main/packages/gatsby-theme-aio/package.json

**Comment by icaraps** [comment] 2021-01-15 16:21
Thanks @shazron  

@emexal-company yes `@adobe/gatsby-theme-aio@2.14.1` was released with the updated dependency.

**Closed by icaraps** 2021-01-15 16:21 UTC
